from typing import NamedTuple
from BaseClasses import Item, ItemClassification

class SonicFrontiersItem(Item):
    game: str = "Sonic Frontiers"

class SonicFrontiersItemData(NamedTuple):
    id: int
    item_class: ItemClassification = ItemClassification.progression

offset: int = 101000
item_list = {
    "Kronos Memory Token": SonicFrontiersItemData(offset, ItemClassification.filler),
    "Kronos Portal Gear": SonicFrontiersItemData(offset + 1, ItemClassification.filler),
    "Kronos Vault Key": SonicFrontiersItemData(offset + 2, ItemClassification.progression),
    "Ares Memory Token": SonicFrontiersItemData(offset + 3, ItemClassification.filler),
    "Ares Portal Gear": SonicFrontiersItemData(offset + 4, ItemClassification.filler),
    "Ares Vault Key": SonicFrontiersItemData(offset + 5, ItemClassification.progression),
    "Chaos Memory Token": SonicFrontiersItemData(offset + 6, ItemClassification.filler),
    "Chaos Portal Gear": SonicFrontiersItemData(offset + 7, ItemClassification.filler),
    "Chaos Vault Key": SonicFrontiersItemData(offset + 8, ItemClassification.progression),
    "Ouranos Memory Token": SonicFrontiersItemData(offset + 9, ItemClassification.filler),
    "Ouranos Portal Gear": SonicFrontiersItemData(offset + 10, ItemClassification.filler), 
    "Ouranos Vault Key": SonicFrontiersItemData(offset + 11, ItemClassification.progression),
    "Kronos Blue Emerald": SonicFrontiersItemData(offset + 12, ItemClassification.progression),
    "Kronos Red Emerald": SonicFrontiersItemData(offset + 13, ItemClassification.progression),
    "Kronos Green Emerald": SonicFrontiersItemData(offset + 14, ItemClassification.progression),
    "Kronos Yellow Emerald": SonicFrontiersItemData(offset + 15, ItemClassification.progression),
    "Kronos Cyan Emerald": SonicFrontiersItemData(offset + 16, ItemClassification.progression),
    "Kronos White Emerald": SonicFrontiersItemData(offset + 17, ItemClassification.progression),
    "Ares Blue Emerald": SonicFrontiersItemData(offset + 18, ItemClassification.progression),
    "Ares Red Emerald": SonicFrontiersItemData(offset + 19, ItemClassification.progression),
    "Ares Green Emerald": SonicFrontiersItemData(offset + 20, ItemClassification.progression),
    "Ares Yellow Emerald": SonicFrontiersItemData(offset + 21, ItemClassification.progression),
    "Ares Cyan Emerald": SonicFrontiersItemData(offset + 22, ItemClassification.progression),
    "Ares White Emerald": SonicFrontiersItemData(offset + 23, ItemClassification.progression),
    "Chaos Blue Emerald": SonicFrontiersItemData(offset + 24, ItemClassification.progression),
    "Chaos Red Emerald": SonicFrontiersItemData(offset + 25, ItemClassification.progression),
    "Chaos Green Emerald": SonicFrontiersItemData(offset + 26, ItemClassification.progression),
    "Chaos Yellow Emerald": SonicFrontiersItemData(offset + 27, ItemClassification.progression),
    "Chaos Cyan Emerald": SonicFrontiersItemData(offset + 28, ItemClassification.progression),
    "Chaos White Emerald": SonicFrontiersItemData(offset + 29, ItemClassification.progression),
    "Ouranos Blue Emerald": SonicFrontiersItemData(offset + 30, ItemClassification.progression),
    "Ouranos Red Emerald": SonicFrontiersItemData(offset + 31, ItemClassification.progression),
    "Ouranos Green Emerald": SonicFrontiersItemData(offset + 32, ItemClassification.progression),
    "Ouranos Yellow Emerald": SonicFrontiersItemData(offset + 33, ItemClassification.progression),
    "Ouranos Cyan Emerald": SonicFrontiersItemData(offset + 34, ItemClassification.progression),
    "Ouranos White Emerald": SonicFrontiersItemData(offset + 35, ItemClassification.progression),
    "Kronos Memory Treasure": SonicFrontiersItemData(offset + 36, ItemClassification.progression),
    "Ares Memory Treasure": SonicFrontiersItemData(offset + 37, ItemClassification.progression),
    "Chaos Memory Treasure": SonicFrontiersItemData(offset + 38, ItemClassification.progression),
    "Ouranos Memory Treasure": SonicFrontiersItemData(offset + 39, ItemClassification.progression),
    "Red Power Seed": SonicFrontiersItemData(offset + 40, ItemClassification.filler),
    "Blue Power Seed": SonicFrontiersItemData(offset + 41, ItemClassification.filler),
    "Kocos (20)": SonicFrontiersItemData(offset + 42, ItemClassification.filler),
    "Phantom Rush": SonicFrontiersItemData(offset + 43, ItemClassification.progression),
    "Air Trick":SonicFrontiersItemData(offset + 44, ItemClassification.progression),
    "Stomp Attack": SonicFrontiersItemData(offset + 45, ItemClassification.progression),
    "Quick Cyloop": SonicFrontiersItemData(offset + 46, ItemClassification.progression),
    "Spin Dash": SonicFrontiersItemData(offset + 47, ItemClassification.progression),
    "Sonic Boom": SonicFrontiersItemData(offset + 48, ItemClassification.progression),
    "Parry": SonicFrontiersItemData(offset + 49, ItemClassification.progression),
    "Homing Shot": SonicFrontiersItemData(offset + 50, ItemClassification.progression),
    "Spin Slash": SonicFrontiersItemData(offset + 51, ItemClassification.progression),
    "Recovery Smash": SonicFrontiersItemData(offset +52, ItemClassification.progression),
    "Cyclone Kick": SonicFrontiersItemData(offset + 53, ItemClassification.progression),
    "Cross Slash": SonicFrontiersItemData(offset + 54, ItemClassification.progression),
    "Grand Slam": SonicFrontiersItemData(offset + 55, ItemClassification.progression),
    "1-2 Unlocked": SonicFrontiersItemData(offset + 56,ItemClassification.progression),
    "1-3 Unlocked": SonicFrontiersItemData(offset + 57,ItemClassification.progression),
    "1-4 Unlocked": SonicFrontiersItemData(offset + 58,ItemClassification.progression),
    "1-5 Unlocked": SonicFrontiersItemData(offset + 59,ItemClassification.progression),
    "1-6 Unlocked": SonicFrontiersItemData(offset + 60,ItemClassification.progression),
    "1-7 Unlocked": SonicFrontiersItemData(offset + 61,ItemClassification.progression),
    "2-1 Unlocked": SonicFrontiersItemData(offset + 62,ItemClassification.progression),
    "2-2 Unlocked": SonicFrontiersItemData(offset + 63,ItemClassification.progression),
    "2-3 Unlocked": SonicFrontiersItemData(offset + 64,ItemClassification.progression),
    "2-4 Unlocked": SonicFrontiersItemData(offset + 65,ItemClassification.progression),
    "2-5 Unlocked": SonicFrontiersItemData(offset + 66,ItemClassification.progression),
    "2-6 Unlocked": SonicFrontiersItemData(offset + 67,ItemClassification.progression),
    "2-7 Unlocked": SonicFrontiersItemData(offset + 68,ItemClassification.progression),
    "3-1 Unlocked": SonicFrontiersItemData(offset + 69,ItemClassification.progression),
    "3-2 Unlocked": SonicFrontiersItemData(offset + 70,ItemClassification.progression),
    "3-3 Unlocked": SonicFrontiersItemData(offset + 71,ItemClassification.progression),
    "3-4 Unlocked": SonicFrontiersItemData(offset + 72,ItemClassification.progression),
    "3-5 Unlocked": SonicFrontiersItemData(offset + 73,ItemClassification.progression),
    "3-6 Unlocked": SonicFrontiersItemData(offset + 74,ItemClassification.progression),
    "3-7 Unlocked": SonicFrontiersItemData(offset + 75,ItemClassification.progression),
    "4-1 Unlocked": SonicFrontiersItemData(offset + 76,ItemClassification.progression),
    "4-2 Unlocked": SonicFrontiersItemData(offset + 78,ItemClassification.progression),
    "4-3 Unlocked": SonicFrontiersItemData(offset + 79,ItemClassification.progression),
    "4-4 Unlocked": SonicFrontiersItemData(offset + 80,ItemClassification.progression),
    "4-5 Unlocked": SonicFrontiersItemData(offset + 81,ItemClassification.progression),
    "4-6 Unlocked": SonicFrontiersItemData(offset + 82,ItemClassification.progression),
    "4-7 Unlocked": SonicFrontiersItemData(offset + 83,ItemClassification.progression),
    "4-8 Unlocked": SonicFrontiersItemData(offset + 84,ItemClassification.progression),
    "4-9 Unlocked": SonicFrontiersItemData(offset + 85,ItemClassification.progression),
}

fixed_amount = {
    "Kronos Memory Treasure": 9,
    "Kronos Vault Key": 5,
    "Ares Memory Treasure": 32,
    "Ares Vault Key": 7,
    "Kronos Blue Emerald": 1,
    "Kronos Red Emerald": 1,
    "Kronos Green Emerald": 1,
    "Kronos Yellow Emerald": 1,
    "Kronos Cyan Emerald": 1,
    "Kronos White Emerald": 1,
    "Ares Blue Emerald": 1,
    "Ares Red Emerald": 1,
    "Ares Green Emerald": 1,
    "Ares Yellow Emerald": 1,
    "Ares Cyan Emerald": 1,
    "Ares White Emerald": 1,
    "1-2 Unlocked" : 1,
    "1-3 Unlocked" : 1,
    "1-4 Unlocked" : 1,
    "1-5 Unlocked" : 1,
    "1-6 Unlocked" : 1,
    "1-7 Unlocked" : 1,
    "2-1 Unlocked" : 1,
    "2-2 Unlocked" : 1,
    "2-3 Unlocked" : 1,
    "2-4 Unlocked" : 1,
    "2-5 Unlocked" : 1,
    "2-6 Unlocked" : 1,
    "2-7 Unlocked" : 1,
    "3-1 Unlocked" : 1,
    "3-2 Unlocked" : 1,
    "3-3 Unlocked" : 1,
    "3-4 Unlocked" : 1,
    "3-5 Unlocked" : 1,
    "3-6 Unlocked" : 1,
    "3-7 Unlocked" : 1,
    "4-1 Unlocked" : 1,
    "4-2 Unlocked" : 1,
    "4-3 Unlocked" : 1,
    "4-4 Unlocked" : 1,
    "4-5 Unlocked" : 1,
    "4-6 Unlocked" : 1,
    "4-7 Unlocked" : 1,
    "4-8 Unlocked" : 1,
    "4-9 Unlocked" : 1,
    "Chaos Memory Treasure": 20,
    "Chaos Vault Key": 8,
    "Ouranos Memory Treasure": 26,
    "Ouranos Vault Key": 8,
    "Chaos Blue Emerald": 1,
    "Chaos Red Emerald": 1,
    "Chaos Green Emerald": 1,
    "Chaos Yellow Emerald": 1,
    "Chaos Cyan Emerald": 1,
    "Chaos White Emerald": 1,
    "Ouranos Blue Emerald": 1,
    "Ouranos Red Emerald": 1,
    "Ouranos Green Emerald": 1,
    "Ouranos Yellow Emerald": 1,
    "Ouranos Cyan Emerald": 1,
    "Ouranos White Emerald": 1,
    "Phantom Rush": 1,
    "Air Trick": 1,
    "Stomp Attack": 1,
    "Quick Cyloop": 1,
    "Spin Dash": 1,
    "Sonic Boom": 1,
    "Parry": 1,
    "Homing Shot": 1,
    "Spin Slash": 1,
    "Recovery Smash": 1,
    "Cyclone Kick": 1,
    "Cross Slash": 1,
    "Grand Slam": 1,
}
fillers = {
    "Red Power Seed": 15,
    "Blue Power Seed": 15,
    "Kocos (20)": 10,
    "Kronos Portal Gear": 5,
    "Kronos Vault Key": 5,
    "Ares Portal Gear": 4,
    "Ares Vault Key": 4,
    "Chaos Vault Key": 3,
    "Chaos Portal Gear": 3,
    "Ouranos Portal Gear": 2,
    "Ouranos Vault Key": 2,
}
#
#traps = {
#    "Water",
#    "Timescale";